include: package:pedantic/analysis_options.yaml
linter:
  rules:
    - unnecessary_const
    - unnecessary_new

    - prefer_const_declarations
    - prefer_const_constructors

    - cancel_subscriptions
    - close_sinks

    - directives_ordering

    - prefer_final_in_for_each

    - provide_deprecation_message
